[project]
name = "malearn"
description = "missingness-avoiding machine learning"
license = "MIT"
license-file = "LICENSE.md"
readme = "README.md"
channels = ["conda-forge", "pytorch", "gurobi"]
platforms = ["linux-64", "osx-64"]

[target.unix.activation.env]
PYTHONPATH = "${PWD}:${PYTHONPATH}"

[dependencies]
python = "3.10.*"
pytorch = {version = ">=2.1.0,<2.2.0", channel = "pytorch"}
matplotlib = ">=3.8.4,<3.9"
seaborn = ">=0.13.2,<0.14"
pandas = ">=2.2.3,<2.3"
numpy = ">=1.18.5,<1.26"
jupyterlab = ">=4.2.2,<4.3"
scikit-learn = ">=1.5.2,<1.6"
skorch = ">=1.0.0,<1.1"
pyyaml = ">=6.0.2,<7"
xgboost = ">=2.1.2,<2.2"
scipy = "==1.9.3"
openpyxl = ">=3.1.5,<3.2"
xlrd = ">=2.0.1,<3"
gurobi = {version = ">=12.0.0,<13", channel = "gurobi"}

# Comment out the lines below if the installation fails on macOS.
[pypi-dependencies]
fastsparsegams = "==0.1.2"

[feature.cuda]
platforms = ["linux-64"]
channels = [
    "nvidia",
    {channel = "pytorch", priority = -1},
    {channel = "rapidsai", priority = -1},
]
system-requirements = {cuda = "12.1"}

[feature.cuda.dependencies]
pytorch-cuda = {version = "12.1.*", channel = "pytorch"}
dask-cuda = {channel = "rapidsai"}

[feature.cpu]
platforms = ["linux-64", "osx-64"]

[feature.test]
platforms = ["linux-64", "osx-64"]

[feature.test.dependencies]
pytest = "*"

[feature.test.tasks]
test = "pytest"

[environments]
cuda = ["cuda"]
default = ["cpu"]
test = ["test"]
